apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-secured-infra
  title: Terraform – Secured Infra (VPC, S3)
  description: Scaffold a Terraform module for VPC + S3 with encryption.
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Infrastructure Details
      required: [project_name, aws_region, vpc_cidr, s3_bucket_name]
      properties:
        project_name:
          type: string
          title: Project Name
          description: Name prefix for all AWS resources
        aws_region:
          type: string
          title: AWS Region
          default: us-east-1
        vpc_cidr:
          type: string
          title: VPC CIDR
          default: 10.0.0.0/16
        s3_bucket_name:
          type: string
          title: S3 Bucket Name
          description: Globally unique S3 bucket name
        instancetype: 
          type: string
          title: Provide config for compute
          description: Size of vm
        branchsuffix:
          type: string
          title: Unique PR branch Suffix
          description: Leave this if ur creating the TF stack for the first time..
          

  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          project_name: ${{ parameters.project_name }}
          aws_region: ${{ parameters.aws_region }}
          vpc_cidr: ${{ parameters.vpc_cidr }}
          s3_bucket_name: ${{ parameters.s3_bucket_name }}
          instancetype: ${{ parameters.instancetype }}
        

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=tulikatanu&repo=${{ parameters.project_name }}-infra
        repoVisibility: public
    - id: wait
      name: Wait for GitHub to catch up
      action: debug:wait
      input:
        seconds: 5    
    - id: register
      name: Register Infra in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}



    
    
    #In prod , we add a condition in prev steps if the github repo already exists or not than creates a PR for every change ... 
    # - id: publish
    #   name: Create PR on existing repo
    #   action: publish:github:pull-request
    #   input:
    #     repoUrl: github.com?owner=tulikatanu&repo=${{ parameters.project_name }}-infra
    #     branchName: "scaffolder-${{ parameters.project_name }}-${{ parameters.branchsuffix }}"
    #     title: "Infra Update for ${{ parameters.project_name }}"
    #     description: "Automatic scaffolder update."

        
  output:
    links:
      - title: GitHub Repository
        url: ${{ steps['publish'].output.remoteUrl }}
